In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#load the data
data=pd.read_csv("EmployeeAttrition.csv")

In [3]:
data.head()

Education JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0        College           High         2            1102              5993.0   
1  Below College         Medium         2             279              5130.0   
2        College         Medium         1            1373              2090.0   
3         Master           High         1            1392              2909.0   
4  Below College           High         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [4]:
data.columns

Index(['Education', 'JobInvolvement', 'JobLevel', 'DailyRate(USD)',
       'MonthlyIncome(USD)', 'NoofCompaniesWorked', 'TotalWorkingYears',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrentManager', 'TrainingTimesLastYear', 'PerformanceRating',
       'Attrition'],
      dtype='object')

In [5]:
data.shape

(1470, 14)

In [6]:
# Finding information of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
Education                  1470 non-null object
JobInvolvement             1466 non-null object
JobLevel                   1470 non-null int64
DailyRate(USD)             1470 non-null int64
MonthlyIncome(USD)         1466 non-null float64
NoofCompaniesWorked        1470 non-null int64
TotalWorkingYears          1470 non-null int64
YearsAtCompany             1470 non-null int64
YearsInCurrentRole         1470 non-null int64
YearsSinceLastPromotion    1470 non-null int64
YearsWithCurrentManager    1470 non-null int64
TrainingTimesLastYear      1470 non-null int64
PerformanceRating          1470 non-null object
Attrition                  1470 non-null object
dtypes: float64(1), int64(9), object(4)
memory usage: 160.9+ KB


In [7]:
# Finding null values
data.isnull().sum()

Education                  0
JobInvolvement             4
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         4
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [8]:
# Handling null values
data['JobInvolvement'].fillna(data['JobInvolvement'].mode()[0],inplace=True)
data['MonthlyIncome(USD)'].fillna(data['MonthlyIncome(USD)'].mean(),inplace=True)

In [9]:
data.isnull().sum()

Education                  0
JobInvolvement             0
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         0
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [10]:
data.describe()

JobLevel  DailyRate(USD)  MonthlyIncome(USD)  NoofCompaniesWorked  \
count  1470.000000     1470.000000         1470.000000          1470.000000   
mean      2.063946      802.485714         6503.751023             2.693197   
std       1.106940      403.509100         4703.975646             2.498009   
min       1.000000      102.000000         1009.000000             0.000000   
25%       1.000000      465.000000         2914.750000             1.000000   
50%       2.000000      802.000000         4936.000000             2.000000   
75%       3.000000     1157.000000         8368.500000             4.000000   
max       5.000000     1499.000000        19999.000000             9.000000   

       TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
count        1470.000000     1470.000000         1470.000000   
mean           11.279592        7.008163            4.229252   
std             7.780782        6.126525            3.623137   
min             0.000000        0.000000            0.000000   
25%             6.000000        3.000000            2.000000   
50%            10.000000        5.000000            3.000000   
75%            15.000000        9.000000            7.000000   
max            40.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  
count              1470.000000              1470.000000            1470.000000  
mean                  2.187755                 4.123129               2.799320  
std                   3.222430                 3.568136               1.289271  
min                   0.000000                 0.000000               0.000000  
25%                   0.000000                 2.000000               2.000000  
50%                   1.000000                 3.000000               3.000000  
75%                   3.000000                 7.000000               3.000000  
max                  15.000000                17.000000               6.000000

In [11]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Education']=le.fit_transform(data['Education'])
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
data['PerformanceRating']=le.fit_transform(data['PerformanceRating'])
data['Attrition']=le.fit_transform(data['Attrition'])

In [12]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  Attrition  
0                  0          1  
1                  1          0  
2                  0          1  
3                  0          0  
4                  0          0

In [13]:
data.shape

(1470, 14)

In [14]:
# Split the data into independent and dependent 
x=data.iloc[:,0:13]
y=data.iloc[:,[13]]

In [15]:
# Split the data into train & test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1176, 13)
(1176, 1)
(294, 13)
(294, 1)


In [16]:
# Feature selection
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x_train,y_train)
mi

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0.        , 0.00694589, 0.01315861, 0.01111108, 0.04183387,
       0.01284158, 0.03212   , 0.01594944, 0.01813194, 0.00408483,
       0.03485264, 0.        , 0.        ])

In [17]:
MI=pd.Series(mi)
MI.index=x_train.columns
MI.sort_values(ascending=False)

MonthlyIncome(USD)         0.041834
YearsWithCurrentManager    0.034853
TotalWorkingYears          0.032120
YearsInCurrentRole         0.018132
YearsAtCompany             0.015949
JobLevel                   0.013159
NoofCompaniesWorked        0.012842
DailyRate(USD)             0.011111
JobInvolvement             0.006946
YearsSinceLastPromotion    0.004085
PerformanceRating          0.000000
TrainingTimesLastYear      0.000000
Education                  0.000000
dtype: float64

In [18]:
# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
y_pred=logr.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[245,  49],
       [  0,   0]], dtype=int64)

In [22]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       294
           1       0.00      0.00      0.00         0

    accuracy                           0.83       294
   macro avg       0.50      0.42      0.45       294
weighted avg       1.00      0.83      0.91       294



C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [23]:
# Decision Tree Classifier

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [25]:
y_pred=dtc.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [27]:
accuracy_score(y_pred,y_test)


0.7312925170068028

In [28]:
confusion_matrix(y_pred,y_test)

array([[205,  39],
       [ 40,  10]], dtype=int64)

In [29]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       244
           1       0.20      0.20      0.20        50

    accuracy                           0.73       294
   macro avg       0.52      0.52      0.52       294
weighted avg       0.73      0.73      0.73       294



In [30]:
# Random Forest Classifier

In [31]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [32]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [33]:
y_pred=rfc.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.8333333333333334

In [35]:
confusion_matrix(y_test,y_pred)

array([[239,   6],
       [ 43,   6]], dtype=int64)

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.98      0.91       245
           1       0.50      0.12      0.20        49

    accuracy                           0.83       294
   macro avg       0.67      0.55      0.55       294
weighted avg       0.79      0.83      0.79       294



In [37]:
# KNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier()

knn.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [39]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [40]:
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8197278911564626

In [42]:
y_train_pred=knn.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
accuracy_score(y_train,y_train_pred)

0.8579931972789115

In [44]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[234  11]
 [ 42   7]]


In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix1 = confusion_matrix(y_train,y_train_pred)
print(confusion_matrix1)

[[961  27]
 [140  48]]


In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90       245
           1       0.39      0.14      0.21        49

    accuracy                           0.82       294
   macro avg       0.62      0.55      0.55       294
weighted avg       0.77      0.82      0.78       294



In [48]:
# svm

In [49]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [50]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.svm import SVC 
svm = SVC() 
svm.fit(x_train, y_train) 

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [51]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [52]:
y_pred = svm.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8333333333333334

In [54]:
y_pred_train=svm.predict(x_train)
accuracy_score(y_train,y_pred_train)

1.0

In [55]:
y_train_pred=svm.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [56]:
accuracy_score(y_train,y_train_pred)

1.0

In [57]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [58]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))



[[245   0]
 [ 49   0]]


In [59]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91       245
           1       0.00      0.00      0.00        49

    accuracy                           0.83       294
   macro avg       0.42      0.50      0.45       294
weighted avg       0.69      0.83      0.76       294



C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [60]:
# Naive Bayes

In [61]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

nb.fit(x_train,y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [62]:
y_pred=nb.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0])

In [63]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7312925170068028

In [64]:
y_train_pred=nb.predict(x_train)
y_train_pred

array([0, 1, 0, ..., 0, 1, 0])

In [65]:
accuracy_score(y_train,y_train_pred)

0.6938775510204082

In [66]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [67]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))



[[191  54]
 [ 25  24]]


In [68]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.78      0.83       245
           1       0.31      0.49      0.38        49

    accuracy                           0.73       294
   macro avg       0.60      0.63      0.60       294
weighted avg       0.79      0.73      0.75       294



In [69]:
# Hyper parameter tunning

In [70]:
from sklearn.model_selection import GridSearchCV
grid_param={ 
    'criterion':['gini','entropy'],
    'max_depth' : [ 5,6,7] 
}
grid_search=GridSearchCV(estimator=dtc,param_grid=grid_param,cv=5,n_jobs=-1)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7]},
             pre_dispatch='2*

In [71]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 5}

In [72]:
dtc_hyper=DecisionTreeClassifier(criterion='entropy',max_depth=5)
dtc_hyper.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [73]:
y_pred_hyper=dtc_hyper.predict(x_test)
accuracy_score(y_test,y_pred_hyper)

0.8129251700680272

In [74]:
confusion_matrix(y_pred,y_test)

array([[191,  25],
       [ 54,  24]], dtype=int64)

In [75]:
confusion_matrix(y_pred_hyper,y_test)

array([[237,  47],
       [  8,   2]], dtype=int64)